---
name: Terraform Check

description: |
  Run Checkov on Terraform plan.

inputs:
  working-directory:
    description: The directory where to run `terraform` commands
    required: true
  tfplan:
    description: Name of the tfplan file to use
    required: true
  upload-sarif:
    description: Upload SARIF?
    required: false
    default: "true"
  results-file:
    description: Name of the results file to use
    required: false
    default: ""
  checkov-skip-check:
    description: Comma-separated list of checkov rules to skip
    required: false
    default: ""

runs:
  using: composite

  steps:
    - name: Install jq if needed
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install --yes --quiet jq
        fi

    - name: Install checkov if needed
      shell: bash
      run: |
        if ! command -v pipx &> /dev/null; then
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install --yes --quiet pipx
        fi
        if ! command -v checkov &> /dev/null; then
          pipx install checkov
        fi

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Inspect ${{ inputs.tfplan }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform show -json ${{ inputs.tfplan }} | jq '.' > ${{ inputs.tfplan }}.json

    - name: Results name
      id: results-name
      shell: bash
      env:
        RESULTS_FILE: ${{ inputs.results-file }}
        TFPLAN_FILE: ${{ inputs.tfplan }}
      run: |
        if [ -z "${RESULTS_FILE}" ]; then
          RESULTS_FILE="${TFPLAN_FILE}.checkov.results.sarif"
        fi
        echo "filename=${RESULTS_FILE}" >> "${GITHUB_OUTPUT}"

    - name: Checkov
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        RESULTS_FILE: ${{ steps.results-name.outputs.filename }}
        CKV_SKIP_CHECK: ${{ inputs.checkov-skip-check }}
      run: |
        checkov \
            --file ${{ inputs.tfplan }}.json \
            --repo-root-for-plan-enrichment . \
            --download-external-modules true \
            --deep-analysis \
            --soft-fail \
            --output sarif \
            --output-file-path "${RESULTS_FILE}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.working-directory }}/${{ steps.results-name.outputs.filename }}
        name: ${{ steps.results-name.outputs.filename }}

    - name: Upload SARIF file
      if: ${{ fromJSON(inputs.upload-sarif) }}
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: ${{ inputs.working-directory }}/${{ steps.results-name.outputs.filename }}
