---
name: Terraform Check

description: |
  Run Checkov on Terraform plan.

inputs:
  working-directory:
    description: The directory where to run `terraform` commands
    required: true
    type: string
  tfplan:
    description: Name of the tfplan file to use
    required: true
    type: string
  upload-sarif:
    description: Upload SARIF?
    required: false
    type: boolean
    default: true

runs:

  using: composite

  steps:

    - name: Install jq if needed
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update > /dev/null 2>&1
          sudo apt-get install --yes --quiet jq
        fi

    - name: Install checkov if needed
      shell: bash
      run: |
        if ! command -v checkov &> /dev/null; then
          sudo pip3 install checkov > /dev/null 2>&1
        fi

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Inspect ${{ inputs.tfplan }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform show -json ${{ inputs.tfplan }} | jq '.' > ${{ inputs.tfplan }}.json

    - name: Checkov
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        checkov \
            --file ${{ inputs.tfplan }}.json \
            --repo-root-for-plan-enrichment . \
            --download-external-modules true \
            --deep-analysis \
            --soft-fail \
            --output sarif \
            --output-file-path checkov.results.sarif

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.working-directory }}/checkov.results.sarif
        name: checkov.results.sarif

    - name: Upload SARIF file
      if: ${{ inputs.upload-sarif }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ inputs.working-directory }}/checkov.results.sarif
