#!/usr/bin/env bash

set -o nounset -o errexit -o pipefail

if ! command -v aws &> /dev/null; then
    echo "error: aws is not available" >&2
    exit 1
fi

TASK_DEFINITION_FAMILY="${TASK_DEFINITION_FAMILY:-}"
CONTAINER_NAME="${CONTAINER_NAME:-}"
CONTAINER_PORT="${CONTAINER_PORT:-}"

function get_task_definition_arn() {
    local task_def_family="${1}"
    aws ecs describe-task-definition \
        --task-definition "${task_def_family}" \
        --query 'taskDefinition.taskDefinitionArn' \
        --output text
}

function render_appspec() {
    local task_def_arn="${1}"
    local container_name="${2}"
    local container_port="${3}"

    appspec_json='{
      "version": 0.0,
      "Resources": [
        {
          "TargetService": {
            "Type": "AWS::ECS::Service",
            "Properties": {
              "TaskDefinition": "'${task_def_arn}'",
              "LoadBalancerInfo": {
                  "ContainerName": "'${container_name}'",
                  "ContainerPort": '${container_port}'
                }
            }
          }
        }
      ]
    }'

    echo "${appspec_json}" | tr --delete  '[:space:]'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    required_env_vars=(
      "TASK_DEFINITION_FAMILY"
      "CONTAINER_NAME"
      "CONTAINER_PORT"
    )

    for var in "${required_env_vars[@]}"; do
        if [ -z "${!var}" ]; then
            echo "error: ${var} is required but not set" >&2
            exit 1
        fi
    done

    TASK_DEFINITION_ARN=$(get_task_definition_arn "${TASK_DEFINITION_FAMILY}")
    render_appspec "${TASK_DEFINITION_ARN}" "${CONTAINER_NAME}" "${CONTAINER_PORT}"
fi
