---
name: Push Amazon ECR Image
description: Build and push a container image to Amazon ECR

inputs:
  aws-region:
    description: The AWS region to use
    required: false
    default: us-east-1
  parent-role-to-assume:
    description: (Optional) Parent IAM role to assume
    required: false
    default: ""
  parent-role-chaining:
    description: (Optional) Enable parent role chaining?
    required: false
    default: "false"
  role-to-assume:
    description: (Optional) IAM role to assume
    required: false
    default: ""
  role-chaining:
    description: (Optional) Enable role chaining?
    required: false
    default: "false"
  ecr-repo-name:
    description: The name of the ECR repository
    required: true
  ecr-registry-type:
    description: The type of ECR registry, private or public
    required: false
    default: private
  image-default-tag:
    description: The default tag to use for the image
    required: false
    default: latest
  add-image-default-tag:
    description: Whether to add the default tag to the image
    required: false
    default: "true"
  mutate-image-default-tag:
    description: Whether to mutate the default tag on the image
    required: false
    default: "true"
  mutate-image-tag:
    description: Whether to mutate the tag on the image
    required: false
    default: "true"
  image-tag-suffix:
    description: Add a suffix to all image tags
    required: false
    default: ""
  use-hash:
    description: Whether to use the commit hash for the image tag; overriden by use-short-hash
    required: false
    default: "true"
  use-short-hash:
    description: Whether to use a short hash for the image tag
    required: false
    default: "false"
  short-hash-length:
    description: The length of the short hash
    required: false
    default: "7"
  setup-docker-buildx:
    description: Whether to set up Docker Buildx
    required: false
    default: "true"
  setup-qemu:
    description: Whether to set up QEMU
    required: false
    default: "false"
  context-dir:
    description: The directory for Docker build context
    required: false
    default: ${{ github.workspace }}
  dockerfile:
    description: The path to the Dockerfile
    required: false
    default: ""
  build-args:
    description: Docker build args (list of --build-arg)
    required: false
    default: ""
  platforms:
    description: Docker platforms comma-separated list (--platform)
    required: false
    default: linux/amd64,linux/arm64

outputs:
  image:
    description: The full image tag published to ECR
    value: ${{ steps.image-names.outputs.image }}
  images:
    description: |
      Comma-separated list of tags published to ECR,
      including the full image tag and the default tag if included
    value: ${{ steps.image-names.outputs.images }}

runs:
  using: composite

  steps:
    - name: Timestamp
      shell: bash
      run: |
        echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

    - name: Platforms
      shell: bash
      env:
        PLATFORMS: ${{ inputs.platforms }}
      run: |
        PLATFORM_AMD64="false"
        PLATFORM_ARM64="false"
        [ "${PLATFORMS#*linux/amd64}" != "$PLATFORMS" ] && PLATFORM_AMD64="true"
        [ "${PLATFORMS#*linux/arm64}" != "$PLATFORMS" ] && PLATFORM_ARM64="true"
        echo "PLATFORM_AMD64=${PLATFORM_AMD64}" >> $GITHUB_ENV
        echo "PLATFORM_ARM64=${PLATFORM_ARM64}" >> $GITHUB_ENV

    - name: Set up QEMU
      if: ${{ inputs.setup-qemu == 'true' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: ${{ inputs.setup-docker-buildx == 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      if: ${{ github.event_name != 'pull_request' && startsWith(inputs.parent-role-to-assume, 'arn:aws:iam::') }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.parent-role-to-assume }}
        role-chaining: ${{ fromJSON(inputs.parent-role-chaining) }}

    - name: Configure AWS Credentials
      if: ${{ github.event_name != 'pull_request' && startsWith(inputs.role-to-assume, 'arn:aws:iam::') }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-chaining: ${{ fromJSON(inputs.role-chaining) }}

    - name: Login to Amazon ECR
      if: ${{ github.event_name != 'pull_request' }}
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: ${{ inputs.ecr-registry-type }}

    - name: Set Dockerfile
      id: set-dockerfile
      shell: bash
      env:
        CONTEXT_DIR: ${{ inputs.context-dir }}
        DOCKERFILE: ${{ inputs.dockerfile }}
      run: |
        if [ -z "${DOCKERFILE}" ]; then
          DOCKERFILE="${CONTEXT_DIR}/Dockerfile"
        fi
        echo "dockerfile=${DOCKERFILE}" >> $GITHUB_OUTPUT

    - name: Format image names
      id: image-names
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
        USE_HASH: ${{ inputs.use-hash }}
        USE_SHORT_HASH: ${{ inputs.use-short-hash }}
        SHORT_HASH_LENGTH: ${{ inputs.short-hash-length }}
        IMAGE_DEFAULT_TAG: ${{ inputs.image-default-tag }}
        ADD_IMAGE_DEFAULT_TAG: ${{ inputs.add-image-default-tag }}
        MUTATE_IMAGE_DEFAULT_TAG: ${{ inputs.mutate-image-default-tag }}
        MUTATE_IMAGE_TAG: ${{ inputs.mutate-image-tag }}
        CONTAINER_REGISTRY: ${{ github.event_name != 'pull_request' && steps.ecr-login.outputs.registry || '' }}
        CONTAINER_REPO_BASE_NAME: ${{ inputs.ecr-repo-name }}
        REGISTRY_TYPE: ${{ inputs.ecr-registry-type }}
        IMAGE_TAG_SUFFIX: ${{ inputs.image-tag-suffix }}
      run: |
        if [ "${USE_SHORT_HASH}" = "true" ]; then
          IMAGE_TAG="${GITHUB_SHA::${SHORT_HASH_LENGTH}}"
        elif [ "${USE_HASH}" = "true" ]; then
          IMAGE_TAG="${GITHUB_SHA}"
        fi

        if [ -n "${IMAGE_TAG}" ]; then
          IMAGE_TAG="${IMAGE_TAG}${IMAGE_TAG_SUFFIX}"
          if [ "${REGISTRY_TYPE}" = "private" ] && [ "${MUTATE_IMAGE_TAG}" = "false" ]; then
            EXISTING_TAG=$(
              aws ecr list-images \
                --repository-name "${CONTAINER_REPO_BASE_NAME}" \
                --query "imageIds[?imageTag=='${IMAGE_TAG}'].imageTag" \
                --output text | tr -d '\n'
            )
            [ -n "${EXISTING_TAG}" ] && unset IMAGE_TAG && unset EXISTING_TAG
          fi
        fi

        if [ "${ADD_IMAGE_DEFAULT_TAG}" = "false" ]; then unset IMAGE_DEFAULT_TAG; fi

        if [ "${ADD_IMAGE_DEFAULT_TAG}" = "true" ]; then
          IMAGE_DEFAULT_TAG="${IMAGE_DEFAULT_TAG}${IMAGE_TAG_SUFFIX}"
          if [ "${REGISTRY_TYPE}" = "private" ] && [ "${MUTATE_IMAGE_DEFAULT_TAG}" = "false" ]; then
            EXISTING_TAG=$(
              aws ecr list-images \
                --repository-name "${CONTAINER_REPO_BASE_NAME}" \
                --query "imageIds[?imageTag=='${IMAGE_DEFAULT_TAG}'].imageTag" \
                --output text | tr -d '\n'
            )
            [ -n "${EXISTING_TAG}" ] && unset IMAGE_DEFAULT_TAG && unset EXISTING_TAG
          fi
        fi

        if [ "${EVENT}" = "pull_request" ]; then
          CONTAINER_REPO_NAME="${CONTAINER_REPO_BASE_NAME}"
        else
          CONTAINER_REPO_NAME="${CONTAINER_REGISTRY}/${CONTAINER_REPO_BASE_NAME}"
        fi

        if [ -n "${IMAGE_TAG}" ]; then
          IMAGE="${CONTAINER_REPO_NAME}:${IMAGE_TAG}"
        fi

        if [ -n "${IMAGE_DEFAULT_TAG}" ]; then
          IMAGE_DEFAULT="${CONTAINER_REPO_NAME}:${IMAGE_DEFAULT_TAG}"
        fi

        if [ -n "${IMAGE}" ] && [ -n "${IMAGE_DEFAULT}" ]; then
          image="${IMAGE}"
          images="${IMAGE},${IMAGE_DEFAULT}"
        elif [ -n "${IMAGE}" ]; then
          image="${IMAGE}"
          images="${IMAGE}"
        elif [ -n "${IMAGE_DEFAULT}" ]; then
          image="${IMAGE_DEFAULT}"
          images="${IMAGE_DEFAULT}"
        else
          >&2 echo "No valid image tag selected."
          exit 1
        fi

        echo "image=${image}" >> $GITHUB_OUTPUT
        echo "images=${images}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v6
      env:
        SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
      with:
        platforms: ${{ inputs.platforms }}
        context: ${{ inputs.context-dir }}
        file: ${{ steps.set-dockerfile.outputs.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.image-names.outputs.images }}
        build-args: ${{ inputs.build-args }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Tag arm64
      uses: docker/build-push-action@v6
      if: ${{ github.event_name != 'pull_request' && env.PLATFORM_ARM64 == 'true' }}
      env:
        SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
      with:
        platforms: linux/arm64
        context: ${{ inputs.context-dir }}
        file: ${{ steps.set-dockerfile.outputs.dockerfile }}
        push: true
        tags: "${{ steps.image-names.outputs.image }}-arm64"
        build-args: ${{ inputs.build-args }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Tag x86_64
      uses: docker/build-push-action@v6
      if: ${{ github.event_name != 'pull_request' && env.PLATFORM_AMD64 == 'true'  }}
      env:
        SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
      with:
        platforms: linux/amd64
        context: ${{ inputs.context-dir }}
        file: ${{ steps.set-dockerfile.outputs.dockerfile }}
        push: true
        tags: "${{ steps.image-names.outputs.image }}-x86_64"
        build-args: ${{ inputs.build-args }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
