---
name: Helm Chart Upgrade via PR

description: |
  Checkout a GitHub repository, upgrade a specified Helm chart within it,
  and create a PR with the changes.

inputs:
  chart-dir:
    description: File system path of the Helm chart directory
    required: true
  chart-name:
    description: Name of the Helm chart
    required: true
  chart-version:
    description: Chart version to set (.version in Chart.yaml)
    required: false
    default: ""
  app-version:
    description: Application version to set (.appVersion in Chart.yaml)
    required: false
    default: ""
  token:
    description: GitHub token with write access to the Helm chart repository
    required: true
  repository:
    description: Repository name
    required: true
  ref:
    description: Branch name
    required: false
    default: main

  branch-name-prefix:
    description: |
      A prefix to prepend to the branch name;
      overrides the default: `auto-`
    required: false
    default: auto-

  branch-name-suffix:
    description: |
      A suffix to append to the branch name;
      overrides the default:
       `-${CHART_VERSION}-${APP_VERSION}`
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check Dependencies
      shell: bash
      run: |
        err_log() {
          >&2 echo "${1}"
        }
        check_cmd() {
          if ! command -v "${1}" &> /dev/null; then
            err_log "error: ${1} command is missing"
            exit 1
          fi
        }
        check_cmd git
        check_cmd yq
        check_cmd gh

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Version
      shell: bash
      working-directory: ${{ inputs.chart-dir }}
      env:
        APP_VERSION: ${{ inputs.app-version }}
        CHART_VERSION: ${{ inputs.chart-version }}
      run: |
        if [ -n "${APP_VERSION}" ]; then
          yq -i ".appVersion = \"${APP_VERSION}\"" "Chart.yaml"
          yq -i ".deployment.image.tag = \"${APP_VERSION}\"" "values.yaml"
        else
          APP_VERSION=$(yq ".appVersion" < "Chart.yaml")
        fi
        echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

        if [ -n "${CHART_VERSION}" ]; then
          yq -i ".version = \"${CHART_VERSION}\"" "Chart.yaml"
        else
          CHART_VERSION=$(yq ".version" < "Chart.yaml")
        fi
        echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV

    - name: Create PR
      shell: bash
      env:
        CHART_NAME: ${{ inputs.chart-name }}
        BRANCH_NAME_PREFIX: ${{ inputs.branch-name-prefix }}
        BRANCH_NAME_SUFFIX: ${{ inputs.branch-name-suffix }}
        BASE: ${{ inputs.ref }}
        GH_TOKEN: ${{ inputs.token }}

        ## github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        ## Sources:
        ## https://github.com/orgs/community/discussions/119597
        ## https://github.com/fregante/setup-git-user/blob/main/action.yml
        GH_ACTIONS_BOT_NAME: github-actions[bot]
        GH_ACTIONS_BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

      run: |
        [ -z "${BRANCH_NAME_SUFFIX}" ] && {
          [ -n "${CHART_VERSION}" ] && BRANCH_NAME_SUFFIX="-${CHART_VERSION}"
          [ -n "${APP_VERSION}" ] && BRANCH_NAME_SUFFIX="${BRANCH_NAME_SUFFIX}-${APP_VERSION}"
        }

        BRANCH_NAME=${BRANCH_NAME_PREFIX}${CHART_NAME}${BRANCH_NAME_SUFFIX}
        TITLE="chore: update ${CHART_NAME} ${CHART_VERSION} ${APP_VERSION}"

        git config user.name "${GH_ACTIONS_BOT_NAME}"
        git config user.email "${GH_ACTIONS_BOT_EMAIL}"

        git checkout -b "${BRANCH_NAME}"

        git add .
        git commit -m "${TITLE}"

        git push origin "${BRANCH_NAME}"

        gh pr create \
          --body "" \
          --title "${TITLE}" \
          --head "${BRANCH_NAME}" \
          --base "${BASE}"
