#!/usr/bin/env bash
# https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html

set -o errexit
set -o pipefail
set -o nounset

TARGETOS="${TARGETOS:-linux}"
TARGETARCH="${TARGETARCH:-amd64}"

if [ "${TARGETARCH}" = "amd64" ]; then export AWS_ARCH="x86_64" ; fi && \
if [ "${TARGETARCH}" = "arm64" ]; then export AWS_ARCH="aarch64" ; fi && \

DOWNLOAD_URL="https://awscli.amazonaws.com/awscli-exe-${TARGETOS}-${AWS_ARCH}.zip"

X_WORKDIR="$(mktemp -d -t awscliv2.XXXXXXXXX)"
X_FILE="${X_WORKDIR}/awscliv2.zip"

function finish {
  rm -rf "${X_WORKDIR}"
}

trap finish EXIT

curl --silent --location --output "${X_FILE}" "${DOWNLOAD_URL}"
unzip -qq "${X_FILE}" -d "${X_WORKDIR}"
cd "${X_WORKDIR}" || exit 1
aws/install
