---
name: Install difftastic

description: Installs difftastic

runs:
  using: composite

  steps:
    - name: Set up script
      shell: bash
      run: |
        SCRIPTS_PATH="${{ github.action_path }}/scripts"
        chmod +x "${SCRIPTS_PATH}/install-difftastic.sh"
        echo "${SCRIPTS_PATH}" >> $GITHUB_PATH
        echo "${HOME}/.local/bin" >> GITHUB_PATH

    - name: Install difftastic
      shell: bash
      run: |
        install-difftastic.sh
