---
name: Upgrade k8s app config via PR

description: |
  Checkout a GitHub repository, upgrade a specified Kubernetes configuration within it,
  and create a PR with the changes.

inputs:
  app-name:
    description: The app name. Used for naming the generated PR branch
    required: true
  app-dir:
    description: File system path of the configuration directory
    required: true
  app-file:
    description: File name to update (must be a YAML file)
    required: true
  app-version:
    description: Application version to set (value in the selected YAML file)
    required: true
  yaml-path:
    description: The YAML path to update with the given app-version
    required: false
    default: .image.tag
  token:
    description: GitHub token with write access to the configuration repository
    required: true
  repository:
    description: Repository name
    required: true
  ref:
    description: Branch name
    required: false
    default: main
  auto-merge:
    description: (Optional) Automatically approve and merge the PR?
    required: false
    default: "false"

  branch-name-prefix:
    description: |
      A prefix to prepend to the branch name;
      overrides the default: `auto-`
    required: false
    default: auto-

  branch-name-suffix:
    description: |
      A suffix to append to the branch name;
      overrides the default: `-${APP_VERSION}`
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check Dependencies
      shell: bash
      run: |
        err_log() {
          >&2 echo "${1}"
        }
        check_cmd() {
          if ! command -v "${1}" &> /dev/null; then
            err_log "error: ${1} command is missing"
            exit 1
          fi
        }
        check_cmd git
        check_cmd yq
        check_cmd gh

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Version
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      env:
        YAML_PATH: ${{ inputs.yaml-path }}
        APP_VERSION: ${{ inputs.app-version }}
        APP_FILE: ${{ inputs.app-file }}
      run: |
        yq -i "${YAML_PATH} = \"${APP_VERSION}\"" "${APP_FILE}"

    - name: Create PR
      shell: bash
      env:
        APP_NAME: ${{ inputs.app-name }}
        APP_VERSION: ${{ inputs.app-version }}
        BRANCH_NAME_PREFIX: ${{ inputs.branch-name-prefix }}
        BRANCH_NAME_SUFFIX: ${{ inputs.branch-name-suffix }}
        BASE: ${{ inputs.ref }}
        GH_TOKEN: ${{ inputs.token }}
        AUTO_MERGE: ${{ inputs.auto-merge }}

        ## github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        ## Sources:
        ## https://github.com/orgs/community/discussions/119597
        ## https://github.com/fregante/setup-git-user/blob/main/action.yml
        GH_ACTIONS_BOT_NAME: github-actions[bot]
        GH_ACTIONS_BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

      run: |
        if [ -z "${BRANCH_NAME_SUFFIX}" ]; then
          BRANCH_NAME_SUFFIX="-${APP_VERSION}"
        fi

        BRANCH_NAME=${BRANCH_NAME_PREFIX}${APP_NAME}${BRANCH_NAME_SUFFIX}
        TITLE="chore: ugrade ${APP_NAME} to ${APP_VERSION}"

        git config user.name "${GH_ACTIONS_BOT_NAME}"
        git config user.email "${GH_ACTIONS_BOT_EMAIL}"

        git checkout -b "${BRANCH_NAME}"

        git add .
        git commit -m "${TITLE}"

        git push origin "${BRANCH_NAME}"

        gh pr create \
          --body "" \
          --title "${TITLE}" \
          --head "${BRANCH_NAME}" \
          --base "${BASE}"

        if [ "${AUTO_MERGE}" == "true" ]; then
          gh pr merge --admin --delete-branch --squash "${BRANCH_NAME}"
        fi
