---
name: Get SSM Parameter
description: Get the value of an SSM parameter

inputs:
  aws-region:
    description: AWS Region
    required: false
    default: us-east-1
  parent-role-to-assume:
    description: (Optional) Parent IAM role to assume
    required: false
    default: ""
  parent-role-chaining:
    description: (Optional) Enable parent role chaining?
    required: false
    default: "false"
  role-to-assume:
    description: (Optional) IAM role to assume
    required: false
    default: ""
  role-chaining:
    description: (Optional) Enable role chaining?
    required: false
    default: "false"
  parameter-name:
    description: The parameter name
    required: true

outputs:
  value:
    value: ${{ steps.get-param.outputs.value }}
    description: The parameter value

runs:
  using: composite

  steps:
    - name: Set up scripts
      shell: bash
      run: |
        SCRIPTS_PATH="${{ github.action_path }}/scripts"
        chmod +x "${SCRIPTS_PATH}/aws-ssm-get-param"
        echo "${SCRIPTS_PATH}" >> $GITHUB_PATH

    - name: Configure AWS Credentials
      if: startsWith(inputs.parent-role-to-assume, 'arn:aws:iam::')
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.parent-role-to-assume }}
        role-chaining: ${{ fromJSON(inputs.parent-role-chaining) }}

    - name: Configure AWS Credentials
      if: startsWith(inputs.role-to-assume, 'arn:aws:iam::')
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-chaining: ${{ fromJSON(inputs.role-chaining) }}

    - name: Get SSM parameter
      shell: bash
      id: get-param
      env:
        PARAM_NAME: ${{ inputs.parameter-name }}
      run: |
        VALUE=$(aws-ssm-get-param "${PARAM_NAME}")
        echo "value=${VALUE}" >> "${GITHUB_OUTPUT}"

    - name: Unset AWS Credentials
      if: startsWith(inputs.role-to-assume, 'arn:aws:iam::') || startsWith(inputs.parent-role-to-assume, 'arn:aws:iam::')
      uses: aws-actions/configure-aws-credentials@v4
      continue-on-error: true
      with:
        aws-region: ${{ inputs.aws-region }}
        unset-current-credentials: true
