---
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      role-chaining:
        required: false
        type: boolean
        default: false
      ecr-repo-name:
        required: true
        type: string
      image-default-tag:
        required: false
        type: string
        default: latest
      add-image-default-tag:
        required: false
        type: boolean
        default: false
      use-hash:
        required: false
        type: boolean
        default: true
      use-short-hash:
        required: false
        type: boolean
        default: false
      short-hash-length:
        required: false
        type: number
        default: 7

      context-dir:
        required: false
        type: string
        default: ${{ github.workspace }}

      dockerfile:
        required: false
        type: string
        default: ""

      matrix-step-name:
        required: false
        type: string
        default: ""

      matrix-key:
        required: false
        type: string
        default: ""

      config-artifact:
        required: false
        type: string
        default: ""
        description: |
          Name of an artifact file containing repository-specific
          configurations, to be saved in the specified directory.
      config-dir:
        required: false
        type: string
        default: ""
        description: |
          Directory where the configuration artifact will
          be saved.

      build-args:
        required: false
        type: string
        default: ""
        description: |
          Docker build args (list of --build-arg)

      ## `image-artifact` is a workaround for the following bug:
      ## [Bug] GitHub Actions does not set job output because it wrongly detects a secret
      ## https://github.com/orgs/community/discussions/37942
      image-artifact:
        required: false
        type: string
        default: image
        description: |
          Name of an artifact file that will contain a string with the full
          image tag to be deployed.

    outputs:
      image-name:
        description: The image name relative to the ECR registry, in the format `<REPO_NAME>:<IMAGE_TAG>`
        value: ${{ jobs.push.outputs.image-name }}
      images:
        description: "Matrix output containing all published images"
        value: ${{ jobs.push.outputs.images }}

jobs:
  push:
    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash

    outputs:
      image-name: ${{ steps.image-build.outputs.image-name }}
      images: ${{ steps.matrix-out.outputs.images }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure path exists ${{ inputs.config-dir }}
        if: ${{ inputs.config-artifact && inputs.config-dir }}
        run: |
          mkdir -p ${{ inputs.config-dir }}

      - name: Download ${{ inputs.config-artifact }}
        uses: actions/download-artifact@v4
        if: ${{ inputs.config-artifact && inputs.config-dir }}
        with:
          name: ${{ inputs.config-artifact }}
          path: ${{ inputs.config-dir }}

      - name: Setup AWS
        uses: andreswebs/gh-actions/.github/actions/aws-bootstrap@main
        with:
          aws-region: ${{ inputs.aws-region }}

      - name: Build and push image to ECR
        id: build
        uses: andreswebs/gh-actions/.github/actions/aws-ecr-push-image@dev
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-chaining: ${{ inputs.role-chaining }}
          ecr-repo-name: ${{ inputs.ecr-repo-name }}
          image-default-tag: ${{ inputs.image-default-tag }}
          add-image-default-tag: ${{ inputs.add-image-default-tag }}
          use-hash: ${{ inputs.use-hash }}
          use-short-hash: ${{ inputs.use-short-hash }}
          short-hash-length: ${{ inputs.short-hash-length }}
          context-dir: ${{ inputs.context-dir }}
          dockerfile: ${{ inputs.dockerfile }}
          build-args: ${{ inputs.build-args }}

      ## Workaround for bug:
      ## [Bug] GitHub Actions does not set job output because it wrongly detects a secret
      ## https://github.com/orgs/community/discussions/37942
      - name: Save image value
        if: inputs.image-artifact
        uses: andreswebs/gh-actions/.github/actions/value-as-artifact@main
        with:
          key: ${{ inputs.image-artifact }}
          value: ${{ steps.build.outputs.image }}

      - name: Matrix Outputs
        id: matrix-out
        uses: cloudposse/github-action-matrix-outputs-write@main
        if: ${{ inputs.matrix-step-name && inputs.matrix-key }}
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}
          matrix-key: ${{ inputs.matrix-key }}
          outputs: |-
            images: ${{ steps.build.outputs.images }}
