---
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      parent-role-to-assume:
        required: false
        type: string
        default: ""
      parent-role-chaining:
        required: false
        type: boolean
        default: false
      role-to-assume:
        required: true
        type: string
      role-chaining:
        required: false
        type: boolean
        default: false
      ecr-repo-name:
        required: true
        type: string
      ecr-registry-type:
        description: The type of ECR registry, private or public
        type: string
        required: false
        default: private
      image-default-tag:
        required: false
        type: string
        default: latest
      add-image-default-tag:
        required: false
        type: boolean
        default: true
      mutate-image-default-tag:
        description: Whether to mutate the default tag on the image
        type: boolean
        required: false
        default: true
      mutate-image-tag:
        description: Whether to mutate the tag on the image
        type: boolean
        required: false
        default: true
      image-tag-suffix:
        description: Add a suffix to all image tags
        type: string
        required: false
        default: ""
      use-hash:
        required: false
        type: boolean
        default: true
      use-short-hash:
        required: false
        type: boolean
        default: false
      short-hash-length:
        required: false
        type: number
        default: 7

      context-dir:
        required: false
        type: string
        default: ${{ github.workspace }}

      dockerfile:
        required: false
        type: string
        default: ""

      config-artifact:
        required: false
        type: string
        default: ""
        description: |
          Name of an artifact file containing repository-specific
          configurations, to be saved in the specified directory.
      config-dir:
        required: false
        type: string
        default: ""
        description: |
          Directory where the configuration artifact will
          be saved.

      build-args:
        required: false
        type: string
        default: ""
        description: |
          Docker build args (list of --build-arg)

      setup-qemu:
        required: false
        type: boolean
        default: false

      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64
        description: Docker platforms comma-separated list (--platform)

      ## `image-artifact` is a workaround for the following bug:
      ## [Bug] GitHub Actions does not set job output because it wrongly detects a secret
      ## https://github.com/orgs/community/discussions/37942
      image-artifact:
        required: false
        type: string
        default: ""
        description: |
          Name of an artifact file that will contain a string with the full
          image tag to be deployed.

jobs:
  push:
    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure path exists ${{ inputs.config-dir }}
        if: ${{ inputs.config-artifact && inputs.config-dir }}
        run: |
          mkdir -p ${{ inputs.config-dir }}

      - name: Download ${{ inputs.config-artifact }}
        uses: actions/download-artifact@v4
        if: ${{ inputs.config-artifact && inputs.config-dir }}
        with:
          name: ${{ inputs.config-artifact }}
          path: ${{ inputs.config-dir }}

      - name: Setup AWS
        uses: andreswebs/gh-actions/.github/actions/aws-bootstrap@main
        with:
          aws-region: ${{ inputs.aws-region }}

      - name: Build and push image to ECR
        id: build
        uses: andreswebs/gh-actions/.github/actions/aws-ecr-push-image@main
        with:
          aws-region: ${{ inputs.aws-region }}
          parent-role-to-assume: ${{ inputs.parent-role-to-assume }}
          parent-role-chaining: ${{ inputs.parent-role-chaining }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-chaining: ${{ inputs.role-chaining }}
          ecr-repo-name: ${{ inputs.ecr-repo-name }}
          ecr-registry-type: ${{ inputs.ecr-registry-type }}
          image-default-tag: ${{ inputs.image-default-tag }}
          image-tag-suffix: ${{ inputs.image-tag-suffix }}
          add-image-default-tag: ${{ inputs.add-image-default-tag }}
          mutate-image-default-tag: ${{ inputs.mutate-image-default-tag }}
          mutate-image-tag: ${{ inputs.mutate-image-tag }}
          use-hash: ${{ inputs.use-hash }}
          use-short-hash: ${{ inputs.use-short-hash }}
          short-hash-length: ${{ inputs.short-hash-length }}
          context-dir: ${{ inputs.context-dir }}
          dockerfile: ${{ inputs.dockerfile }}
          build-args: ${{ inputs.build-args }}
          setup-qemu: ${{ inputs.setup-qemu }}
          platforms: ${{ inputs.platforms }}

      ## Workaround for bug:
      ## [Bug] GitHub Actions does not set job output because it wrongly detects a secret
      ## https://github.com/orgs/community/discussions/37942
      - name: Save image value
        if: ${{ inputs.image-artifact }}
        uses: andreswebs/gh-actions/.github/actions/value-as-artifact@main
        with:
          key: ${{ inputs.image-artifact }}
          value: ${{ steps.build.outputs.image }}
