---
on:
  workflow_call:

    inputs:
      runs-on:
        required: true
        type: string
      matrix-step-name:
        required: true
        type: string
      tfvars:
        required: false
        type: string
        default: images.auto.tfvars

    outputs:
      tfvars:
        description: The filename used to save the `.tfvars` file
        value: ${{ jobs.images-tfvars.outputs.tfvars }}

jobs:

  images-tfvars:
    name: Generate Terraform variables

    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        shell: bash

    outputs:
      tfvars: ${{ steps.parse.outputs.images-tfvars }}

    steps:

      - name: Install jq if not present
        shell: bash
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update 2>&1 > /dev/null
            sudo apt-get install --yes --quiet jq
          fi

      - name: Read matrix outputs
        id: read
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}

      - name: Parse matrix outputs
        id: parse
        run: |
          rm -rf ${{ inputs.tfvars }}
          echo '${{ steps.read.outputs.result }}' | jq -r '.images | to_entries[] | "\(.key|gsub("-";"_")) = \"\(.value)\"" | "image_\(.)"' > ${{ inputs.tfvars }}
          echo "images-tfvars=${{ inputs.tfvars }}" >> $GITHUB_OUTPUT

      - name: Save ${{ steps.parse.outputs.images-tfvars }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.parse.outputs.images-tfvars }}
          path: ${{ steps.parse.outputs.images-tfvars }}
          if-no-files-found: error
